# Site settings
baseurl: "/EA-models"
url: "https://sara-sabr.github.io/"

# Build settings
markdown: kramdown
include: ["reports"]
exclude: ["wip-tec", "CONTRIBUTING.md", "cspell.json", "LICENSE", "link-check.js", "package.json", "package-lock.json", "README.md", "node_modules"]
